# 2-Layers Neural Network

In [21]:
import numpy as np

## Forward propagation

Initializing weights

In [22]:
m=1000000 # Number of training examples
w_layer1=np.random.rand(4,3)*0.001
b_layer1=np.zeros((4,1))
x_input=np.random.rand(3,m)*0.001
y_output=np.random.rand(1,m)
alpha=0.001 # Learning rate
print("w_layer1 :\n"+str(w_layer1))
print("b_layer1 :\n"+str(b_layer1))

w_layer1 :
[[8.31422079e-04 5.12132419e-04 5.44667345e-06]
 [2.76542451e-05 2.60144883e-04 5.06863588e-04]
 [1.38822418e-04 4.19075813e-04 3.84249059e-04]
 [3.35553023e-04 8.15495600e-04 4.24873949e-04]]
b_layer1 :
[[0.]
 [0.]
 [0.]
 [0.]]


In [23]:
w_output=np.random.rand(1,4)
b_output=0

In [24]:
z_layer1=np.add(np.dot(w_layer1,x_input),b_layer1)
print(z_layer1)

[[9.61111953e-07 4.27539681e-07 2.36095350e-07 ... 3.37131451e-07
  4.55387954e-07 6.91725375e-07]
 [5.74750641e-07 5.01481437e-07 4.26564886e-07 ... 1.17263960e-07
  3.37307343e-07 3.36963425e-07]
 [6.84721427e-07 4.53005115e-07 3.86924595e-07 ... 1.37321259e-07
  3.88440789e-07 4.23991048e-07]
 [1.14889266e-06 6.14223784e-07 5.27927007e-07 ... 2.26690178e-07
  6.38852640e-07 7.33622537e-07]]


In [25]:
a_layer1=np.maximum(0,z_layer1)
print(a_layer1)

[[9.61111953e-07 4.27539681e-07 2.36095350e-07 ... 3.37131451e-07
  4.55387954e-07 6.91725375e-07]
 [5.74750641e-07 5.01481437e-07 4.26564886e-07 ... 1.17263960e-07
  3.37307343e-07 3.36963425e-07]
 [6.84721427e-07 4.53005115e-07 3.86924595e-07 ... 1.37321259e-07
  3.88440789e-07 4.23991048e-07]
 [1.14889266e-06 6.14223784e-07 5.27927007e-07 ... 2.26690178e-07
  6.38852640e-07 7.33622537e-07]]


In [26]:
z_output=np.add(np.dot(w_output,a_layer1),b_output)

In [27]:
a_output=np.maximum(0,z_output)
print("Final prediction : \n"+str(z_output))

Final prediction : 
[[2.07566585e-06 1.27467001e-06 9.94136000e-07 ... 5.22095950e-07
  1.11711597e-06 1.34724267e-06]]


## Backpropagation

In [28]:
dz_output=np.subtract(a_output,y_output)
dw_output=np.dot(a_layer1,dz_output.T)/m
db_output=np.sum(dz_output,axis=1,keepdims=True)/m

In [29]:
def reluDerivative(x):
    x[x<0] = 0
    x[x>=0] = 1
    return x
dz_layer1=np.dot(w_output.T,dz_output)*reluDerivative(z_layer1)
dw_layer1=np.dot(x_input,dz_layer1.T)/m
db_output=np.sum(dz_layer1,axis=1,keepdims=True)/m

### Updating all the weights

In [35]:
z_output=np.subtract(z_output,alpha*dz_output)
w_output=np.subtract(w_output,alpha*dw_output)
b_output=np.subtract(b_output,alpha*db_output)

z_layer1=np.subtract(z_layer1,alpha*dz_layer1)
w_layer1=np.subtract(w_layer1,alpha*dw_layer1)
b_layer1=np.subtract(b_layer1,alpha*db_layer1)

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 